// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWlfyAIOxuYNmyU3G_fG_zKVA-v1vyna8',
    appId: '1:335056704408:web:f795326d8a1c09405011ed',
    messagingSenderId: '335056704408',
    projectId: 'meet-c4483',
    authDomain: 'meet-c4483.firebaseapp.com',
    storageBucket: 'meet-c4483.appspot.com',
    measurementId: 'G-5RHZY2V2LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPYTAfqlunppLokjOiZg0ASdiyrfvt8Q',
    appId: '1:335056704408:android:8ae9c4241c2c88105011ed',
    messagingSenderId: '335056704408',
    projectId: 'meet-c4483',
    storageBucket: 'meet-c4483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPLEF2_iyttz8yM1HCBJS-Y9qgPA-_0U',
    appId: '1:335056704408:ios:67be2f3b401cd3da5011ed',
    messagingSenderId: '335056704408',
    projectId: 'meet-c4483',
    storageBucket: 'meet-c4483.appspot.com',
    androidClientId: '335056704408-fvnjfs84138vp3mvhitvcn22ihsegq9p.apps.googleusercontent.com',
    iosClientId: '335056704408-01cl16j8uvn5ndg8nh333q6bchcqp961.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasenewproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTPLEF2_iyttz8yM1HCBJS-Y9qgPA-_0U',
    appId: '1:335056704408:ios:d2a9dabeb026acff5011ed',
    messagingSenderId: '335056704408',
    projectId: 'meet-c4483',
    storageBucket: 'meet-c4483.appspot.com',
    androidClientId: '335056704408-fvnjfs84138vp3mvhitvcn22ihsegq9p.apps.googleusercontent.com',
    iosClientId: '335056704408-3b540cnlg7suvf53o2ii2gmgvs5nmeg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasenewproj.RunnerTests',
  );
}
